baseURL = "https://DEIL111428.github.io/portfolio.github.io/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'

[params]
    # Это поможет теме правильно подхватывать стили
    env = "production"